name: mausam_home
description: Personalized homepage for the Mausam app (SIH26076) - mobile client.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
